/*
  Rewrites ART-REQUESTS.md from the shipped world.

  This exists because the first version of that file was written by hand, from
  reading notes, a day before the generator existed — and it was a curation
  rather than an inventory. It ranked by what had been vivid to read rather
  than by what the world actually uses, so the Hall of Miraculous Mist, the
  throne hall of Heaven and the most-used interior in the book at seven scenes,
  was not on it at all. It then stayed stale across three batches of art while
  the counts underneath it changed.

  A list of what is missing is a query, not an opinion. Run this after every
  batch:

    node scripts/journey-to-the-west/art-gaps.mjs

  The prose at the top is kept by hand — house style and the notes about which
  plates were split are judgements, and belong to a person. Everything below
  the first "## " heading is derived and will be overwritten.
*/
import fs from 'node:fs'

const WORLD = 'public/library/journey-to-the-west.pwk'
const OUT = 'scripts/journey-to-the-west/ART-REQUESTS.md'

const w = JSON.parse(fs.readFileSync(WORLD, 'utf8'))
const chapterNumber = new Map(w.chapters.map((c) => [c.id, c.number]))

/** "ch 74–77" for whatever scenes match, or "—" for an entity in none. */
const chapterSpan = (matches) => {
  const seen = new Set()
  for (const event of w.events) if (matches(event)) seen.add(chapterNumber.get(event.chapterId))
  const all = [...seen].sort((a, b) => a - b)
  if (!all.length) return '—'
  return all.length === 1 ? `ch ${all[0]}` : `ch ${all[0]}–${all[all.length - 1]}`
}

const gaps = (records, imageKey, matches) =>
  records
    .filter((r) => !r[imageKey])
    .map((r) => ({ name: r.name, scenes: w.events.filter((e) => matches(e, r)).length, span: chapterSpan((e) => matches(e, r)) }))
    .sort((a, b) => b.scenes - a.scenes || a.name.localeCompare(b.name))

const characters = gaps(w.characters, 'portraitImageId', (e, c) => e.involvedCharacterIds.includes(c.id))
const places = gaps(w.locationMarkers, 'imageId', (e, l) => e.locationMarkerId === l.id)
const items = gaps(w.items, 'imageId', (e, i) => e.involvedItemIds.includes(i.id))
const factions = w.factions.filter((f) => !f.coverImageId).map((f) => f.name)

const bullets = (rows) => rows.map((r) => `- **${r.name}** (${r.span}, ${r.scenes} ${r.scenes === 1 ? 'scene' : 'scenes'})`).join('\n')
const inline = (rows) => rows.map((r) => `${r.name} (${r.span})`).join(' · ')
const have = (records, key) => `${records.filter((r) => r[key]).length}/${records.length}`

const tier = (heading, rows, note) =>
  rows.length ? `## ${heading}\n\n${bullets(rows)}\n${note ? `\n${note}\n` : ''}\n---\n\n` : ''

const doc = `# Journey to the West — remaining art

**Generated by \`scripts/journey-to-the-west/art-gaps.mjs\` — do not hand-edit
below the first heading.** Re-run it after every batch; a list of what is
missing is a query, not an opinion, and the hand-written version of this file
drifted three times before it was replaced by this one.

${w.blobs.length} images ship with the book: ${have(w.characters, 'portraitImageId')} characters,
${have(w.locationMarkers, 'imageId')} places, ${have(w.items, 'imageId')} items,
${have(w.factions, 'coverImageId')} factions, ${w.mapLayers.length} maps, and a public-domain cover.

House style: the painted, aged-paper look of the cudgel, the White Bone Lady, the
register and the four-continents chart. Landscape 3:2 for maps and places,
portrait 2:3 for figures, square-ish for items. New images may omit lettering to
keep captions in the application accessible and avoid invented text. Preserve
the mature illustrated style, not photography, maps, cartoons or repeated art.

---

${items.length
    ? tier(`Items — ${items.length} left`, items)
    : `## Items — all ${w.items.length} are done\n\nNothing outstanding on objects.\n\n---\n\n`}${tier(
      `Places with three scenes or more — ${places.filter((p) => p.scenes >= 3).length} left`,
      places.filter((p) => p.scenes >= 3),
      'These are the biggest gaps by usage, which is the only ranking that does not\ndepend on what somebody found memorable.',
    )}${tier(
      `Characters with three scenes or more — ${characters.filter((c) => c.scenes >= 3).length} left`,
      characters.filter((c) => c.scenes >= 3),
    )}${characters.filter((c) => c.scenes === 2).length
      ? `## Characters with two scenes — ${characters.filter((c) => c.scenes === 2).length}\n\n${inline(characters.filter((c) => c.scenes === 2))}\n\n---\n\n`
      : ''}${places.filter((p) => p.scenes === 2).length
      ? `## Places with two scenes — ${places.filter((p) => p.scenes === 2).length}\n\n${inline(places.filter((p) => p.scenes === 2))}\n\n---\n\n`
      : ''}${factions.length ? `## Faction covers — ${factions.length} left\n\n${factions.map((f) => `- ${f}`).join('\n')}\n\n---\n\n` : ''}## Less frequently visited entities

${characters.filter((c) => c.scenes === 1).length} characters and ${places.filter((p) => p.scenes === 1).length} places appear in a single scene each, and
${places.filter((p) => p.scenes === 0).length} more places are gateways, continents and seas that carry no scene of
their own. The author has requested additional illustrations for the remaining
entities. Each addition must be a distinct, reviewed depiction of its subject;
a near-miss illustration is not an acceptable substitute (\`EX-302\`).

${bullets(characters.filter((c) => c.scenes <= 1))}

${bullets(places.filter((p) => p.scenes <= 1))}
`

fs.writeFileSync(OUT, `${doc.trimEnd()}\n`)
console.log(`${OUT}: ${characters.length} characters, ${places.length} places, ${items.length} items, ${factions.length} factions`)
